---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fio-multi-job
data:
  fio.job: |
    [global]
    ioengine=psync
    direct=1
    buffered=0
    group_reporting
    refill_buffers
    runtime=60 # Run each job for 60 seconds
    
    [readjob]
    rw=read
    filesize=20G # Specify file size, large enough for the runtime
    numjobs=4
    bs=512K
    filename=testfile.fio
    stonewall
    
    [randwritejob]
    rw=randwrite
    filesize=20G # Specify file size
    numjobs=4
    bs=4K
    filename=testfile.fio
    stonewall
    
    [rwmixjob]
    rw=randrw
    rwmixread=70
    filesize=20G # Specify file size
    numjobs=4
    bs=128K
    filename=testfile.fio
