---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fio-multi-job
data:
  fio.job: |
    [global]
    ioengine=psync
    direct=1
    buffered=0
    group_reporting
    refill_buffers

    [readjob]
    rw=read
    size=10G
    numjobs=4
    bs=512K
    filename=testfile.fio
    stonewall

    [randwritejob]
    rw=randwrite
    size=4G
    numjobs=4
    bs=4K
    filename=testfile.fio
    stonewall

    [rwmixjob]
    rw=randrw
    rwmixread=70
    size=8G
    numjobs=4
    bs=128K
    filename=testfile.fio